### ISSUE TITLE
Every CLI verb crashes: __dict__ on slots dataclasses (ragmark index is broken on dev now)

### ISSUE THREAD

**Issue by cdcoonce** [cdcoonce/ragmark#16]
## Problem

Every CLI verb that prints a result crashes with an unhandled `AttributeError`. `ragmark index` is broken **right now** on `dev` — its seam landed in #7 and merged in #14.

```
$ ragmark --vault <vault> index
Traceback (most recent call last):
  File ".../bin/ragmark", line 10, in <module>
    sys.exit(main())
  File ".../src/ragmark/cli.py", line 105, in main
    print(json.dumps(report.__dict__, default=list, indent=2))
                     ^^^^^^^^^^^^^^^
AttributeError: 'RefreshReport' object has no attribute '__dict__'
```

Every result type in this package is `@dataclass(frozen=True, slots=True)`, and a slots dataclass has no instance `__dict__`. Verified:

| type            | `slots` | used by                                 |
| --------------- | ------- | --------------------------------------- |
| `RefreshReport` | True    | `index` verb — **live on `dev` today**  |
| `SearchHit`     | True    | `search` verb — breaks when #8 lands    |
| `Neighborhood`  | True    | `neighbors` verb — breaks when #9 lands |
| `ActivityEntry` | True    | `recent` verb — breaks when #10 lands   |

The four call sites in `src/ragmark/cli.py`:

- `search`: `json.dumps([hit.__dict__ for hit in hits], indent=2)`
- `neighbors`: `json.dumps(result, default=lambda o: o.__dict__, indent=2)`
- `recent`: `json.dumps([entry.__dict__ for entry in entries], indent=2)`
- `index`: `json.dumps(report.__dict__, default=list, indent=2)`

Two things make this worse than a normal bug:

1. **It escapes the CLI's error boundary.** `cli.py` is supposed to turn failures into a clean exit-2 message — `tests/test_cli.py::test_not_implemented_seam_exits_2_with_message` explicitly asserts `"Traceback" not in captured.err`. This defect bypasses that and dumps a raw traceback at the user.
2. **The whole gate is blind to it.** `tests/test_cli.py` exercises `_build_parser()` and argument parsing only — `test_neighbors_parser_arguments` calls `parser.parse_args([...])` and never `main()`. So no test ever runs a verb's execution path to completion. #7 landed, the full gate passed, six CI legs passed, and the verb it shipped has never once been run.

## What to build

Serialize the dataclasses properly and add a test that actually executes a verb end to end.

- Replace every `__dict__` access in `src/ragmark/cli.py` with `dataclasses.asdict(...)`, which supports slots dataclasses and recurses into nested ones (`Neighborhood.neighbors` is a tuple of `Neighbor`, so the `neighbors` verb needs the recursion — a shallow `vars()` substitute would not do).
- Keep the existing output shape: a JSON list for `search` and `recent`, a JSON object for `neighbors` and `index`. This is a wire format the MCP face and any consumer depend on; do not "improve" the schema while fixing the crash.
- `index`'s call passes `default=list` because `RefreshReport.defects` is a tuple. `asdict` already converts tuples to lists, so confirm whether `default=` is still needed rather than copying it forward blindly.

## Acceptance criteria

- [ ] `ragmark --vault <fixture> index` runs to completion, exits 0, and prints parseable JSON with the `RefreshReport` fields — asserted by a test that calls `main()`, not one that only builds the parser
- [ ] That test lives in `tests/test_cli.py` and drives the real execution path with `monkeypatch.setattr(sys, "argv", ...)`, mirroring the existing `test_not_implemented_seam_exits_2_with_message` pattern
- [ ] A regression test asserts no raw `Traceback` reaches stderr for a successfully-executing verb
- [ ] The test must FAIL against the current `__dict__` code — name that mutation in the PR description and show the failing output
- [ ] The remaining three verbs (`search`, `neighbors`, `recent`) use the same serialization helper, so they cannot regress individually as their seams land
- [ ] The test does not require a warm fastembed model cache — the `index` verb needs an embedder, so either inject a stub or mark it `@pytest.mark.model`; prefer the stub so it runs on all six CI legs
- [ ] Full gate is green

## Out of scope

Do not implement any unimplemented seam. Do not change the output JSON schema, any dataclass definition in `src/ragmark/model.py`, or the MCP face — `mcp.py` already uses `dataclasses.asdict` correctly and needs no change. Do not touch the gate, the chunker, the embedder, or the index.

Part of #1

Target: afk/epic-1

## Budget

~1 slice · tier: cheap
